# Generated by Django 6.0.5 on 2026-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='cours_pdfs/'),
        ),
    ]
