# Generated by Django 6.0.5 on 2026-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_cours_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cours_videos/'),
        ),
    ]
